#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $KC_DB_USER WITH PASSWORD '$KC_DB_PASSWORD';
    CREATE USER $FASTAPI_DB_USER WITH PASSWORD '$FASTAPI_DB_PASSWORD';
    CREATE DATABASE $KC_DB_NAME OWNER $KC_DB_USER;
    CREATE DATABASE $FASTAPI_DB_NAME OWNER $FASTAPI_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $KC_DB_NAME TO $KC_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $FASTAPI_DB_NAME TO $FASTAPI_DB_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$KC_DB_NAME" \
    -c "GRANT ALL ON SCHEMA public TO $KC_DB_USER; ALTER SCHEMA public OWNER TO $KC_DB_USER;"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$FASTAPI_DB_NAME" \
    -c "GRANT ALL ON SCHEMA public TO $FASTAPI_DB_USER; ALTER SCHEMA public OWNER TO $FASTAPI_DB_USER;"

